Remove unused C import for extensions
Summary:
This diff removes the unused MCA header from MBQ extensions

Currently MBQ extensions files are including the C header which is not being used, MBQ extensions will only rely on MBQ assembly to get data.
```
#import <Foundation/Foundation.h>

#import <Typing/MCQThreadListTyping.h> <-- not used

#import <ThreadListQueryObjC/MBQThreadListQuery.h>

NS_ASSUME_NONNULL_BEGIN

static inline int32_t MBQExtensionThreadListWithTypingIndicatorGetFoo(MBQThreadListQuery *resultSet, int32_t row)
{
  return MBQThreadListQueryGetFoo(resultSet, row);
}
```

Beside tat this also is triggering an error only in c++, if you include two or more MBQ extensions in a file, each MCA will contain the result-set declaration

```
cql_result_set_type_decl(MCQThreadListQueryResultSet, MCQThreadListQueryResultSetRef);
```

Leading to a redefinition between the files:

```
redefinition of 'meta<__MCQThreadListQueryResultSet>'
cql_result_set_type_decl(MCQThreadListQueryResultSet, MCQThreadListQueryResultSetRef);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xplat/msys/src_sqlite/MessengerCoreInfrastructure/MCICQLRuntime.h:471:46: note: expanded from macro 'cql_result_set_type_decl'
typedef result_set_type##Ref result_set_ref; \
                                             ^
xplat/msys/src/MessengerCoreFoundation/MCFCppBase.h:103:10: note: expanded from macro '\
MCF_CPP_DEFINE_INTEROP_WITH_STRUCT_TYPEID'
  struct meta<structName> {                                                      \
         ^~~~~~~~~~~~~~~~
buck-out/gen/33fbdb84/xplat/msys/samples/cql_test/Typing_1173416036841602640_b-gen-C_cg/MCQThreadListTyping.h:10:1: note: previous definition is here
cql_result_set_type_decl(MCQThreadListQueryResultSet, MCQThreadListQueryResultSetRef);
^
xplat/msys/src_sqlite/MessengerCoreInfrastructure/MCICQLRuntime.h:471:46: note: expanded from macro 'cql_result_set_type_decl'
typedef result_set_type##Ref result_set_ref; \
                                             ^
xplat/msys/src/MessengerCoreFoundation/MCFCppBase.h:103:10: note: expanded from macro '\
MCF_CPP_DEFINE_INTEROP_WITH_STRUCT_TYPEID'
  struct meta<structName> {
```

This error is exclusive from a c++ compilation, since this same scenario is happening currently in the iOS App and it not complaining. You can see it in D24254873

Reviewed By: ricomariani

Differential Revision: D24238518

fbshipit-source-id: 6de09bd7cc46c4e19692e512f470f4c6e71b47ae