Fix broken cql_tests_legocastle job and test_vscode.sh
Summary:
the buck graph for `cql_tests_legocastle` script now have dependencies to buck targets in `fbandroid`. We need to pull the full `fbsource` repo to run its sandcastle job. Previously we were pulling only `fbsource/xplat/*` repo. Not enough anymore.

I also landed a diff that broke some tests in `test_vscode.py` but was not reported by the previous oncall. I just noticed it now because I'm oncall.

I also updated the chronos script to latest: https://fburl.com/chronos/mi7459a3

```
Failure Found: cql_tests_chronos - Run test_vscode.sh
stdout:
--------------------------------- TEST VSCODE SCRIPT
validate vscode diagnostic command
validate vscode query plan command
validate vscode query plan command for a random msys cql file
validate vscode query plan command for a random msys cql file with only schema statement
validate vscode resolve_cql_deps command
validate vscode find_include_source command for BUCK file
validate vscode find_include_source command for codegen BUCK file
VSCode find_include_source returned unexpected error code
Traceback (most recent call last):
  File "./script/vscode.py", line 528, in <module>
    arguments.func(arguments)
  File "./script/vscode.py", line 450, in _cmd_find_include_source
    rs = _find_include_source_file(arguments.cql_file, namespace, include_file_names)
  File "./script/vscode.py", line 373, in _find_include_source_file
    raise Exception(stderr)
Exception: b'Using additional configuration options from .buckconfig.local, /etc/buckconfig.d/sandcastle\nPARSING BUCK FILES: FINISHED IN 0.6s\nNo build file at fbandroid/apps/generic/BUCK when resolving target //fbandroid/apps/generic:sample_manifest.\n'
stderr:
./test_vscode.sh: line 77: failed: command not found
````

Reviewed By: winniequinn

Differential Revision: D29384922

fbshipit-source-id: c99e3ff67b26da48cc983da3546887f4cb5a9afe